### ISSUE TITLE
Error in retrieving the decryption key used to decrypt

### ISSUE THREAD

**Issue by subhendukundu** [agnostech/flutter_amplify#3]
I just started a new flutter project where I am adding the AWS Cognito following https://agnostech.github.io/flutteramplify/#/authentication

I have added amplify auth which added the awsconfiguration.json.
My login page looks like
```
import 'package:flutter/material.dart';
import 'package:fugit/src/app.dart';
import 'package:fugit/src/views/pages/home_page.dart';
import 'package:flutter_aws_amplify_cognito/flutter_aws_amplify_cognito.dart';

class LoginPage extends StatefulWidget {
  @override
  _LoginPageState createState() => _LoginPageState();
}

class _LoginPageState extends State<LoginPage> {
  @override
  void initState() {
    FlutterAwsAmplifyCognito.initialize().then((UserStatus status) {
      print(status);
    }).catchError((error) {
      print(error);
    });
    super.initState();
  }
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: RaisedButton(
          onPressed: () {
            // Navigate to Home Page
            Navigator.push(context, MaterialPageRoute(builder: (context) {
              return App();
            }));
          },
          child: Text("Login"),
        ),
      ),
    );
  }
}

```
But when I try to start the app I am getting the following error on Android.
E/AWSKeyValueStore( 4177): Error in retrieving the decryption key used to decrypt the data from the persistent store. Returning null for the requested dataKey = ap-south-1

How do I fix it?
Thanks

**Comment by vishal-android-freak** [comment]
Have you tried setting up auth first?
https://agnostech.github.io/flutteramplify/#/authentication?id=android

Also, it's just a warning at the beginning because you have just initialized Amplify Auth. Once you login the keys will be generated and will be saved. Next time onwards these keys will be used :)

**Comment by subhendukundu** [comment]
Well the app didnt open up at all. I am missing something? I followed the same steps as added in the document.
1.  cd android
2. amplify init
3. amplify add auth
4. amplify push
which created all the details.
And added the following code for my login
```
import 'package:flutter/material.dart';
import 'package:myapp/src/app.dart';
import 'package:myapp/src/views/pages/home_page.dart';
import 'package:flutter_aws_amplify_cognito/flutter_aws_amplify_cognito.dart';

class LoginPage extends StatefulWidget {
  @override
  _LoginPageState createState() => _LoginPageState();
}

class _LoginPageState extends State<LoginPage> {
  @override
  void initState() {
    FlutterAwsAmplifyCognito.initialize().then((UserStatus status) {
      print(status);
    }).catchError((error) {
      print(error);
    });
    super.initState();
  }
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: RaisedButton(
          onPressed: () {
            // Navigate to Home Page
            Navigator.push(context, MaterialPageRoute(builder: (context) {
              return App();
            }));
          },
          child: Text("Login"),
        ),
      ),
    );
  }
}

```

**Comment by vishal-android-freak** [comment]
Does the app crash after this? Remember, this code just initializes the library code. You haven't written anything to log in or sign up for the user.

**Comment by subhendukundu** [comment]
App crashes with just
```
void initState() {
    FlutterAwsAmplifyCognito.initialize().then((UserStatus status) {
      print(status);
    }).catchError((error) {
      print(error);
    });
    super.initState();
  }
```
I remove the code, it works.
I could see errors like
```
Error in retrieving the decryption key used to decrypt the data from the persistent store. Returning null for the requested dataKey = ap-south-1:#########-#####_#######.expirationDate
```
then
```
Error in retrieving the decryption key used to decrypt the data from the persistent store. Returning null for the requested dataKey = hostedUI
W/AWSMobileClient( 8034): Failed to parse HostedUI settings from store. Defaulting to awsconfiguration.json
W/AWSMobileClient( 8034): java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
W/AWSMobileClient( 8034): 	at org.json.JSONTokener.nextCleanInternal(JSONTokener.java:116)
W/AWSMobileClient( 8034): 	at org.json.JSONTokener.nextValue(JSONTokener.java:94)
W/AWSMobileClient( 8034): 	at org.json.JSONObject.<init>(JSONObject.java:156)
W/AWSMobileClient( 8034): 	at org.json.JSONObject.<init>(JSONObject.java:173)
W/AWSMobileClient( 8034): 	at com.amazonaws.mobile.client.AWSMobileClient.getHostedUIJSON(AWSMobileClient.java:663)
W/AWSMobileClient( 8034): 	at com.amazonaws.mobile.client.AWSMobileClient$2.run(AWSMobileClient.java:565)
W/AWSMobileClient( 8034): 	at com.amazonaws.mobile.client.internal.InternalCallback$1.run(InternalCallback.java:101)
W/AWSMobileClient( 8034): 	at java.lang.Thread.run(Thread.java:761)
```
```
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.amazonaws.mobileconnectors.cognitoauth.Auth$Builder"
```
This is so new to me. :(

**Comment by vishal-android-freak** [comment]
Ahh, got it, you have also configured OAuth UI of federated login. Hence, the crash. We don't support login UI in this library right now. Check your `awsconfiguration.json`

```json
{
        "IdentityManager": {
            "Default": {}
        },
        "CredentialsProvider": {
            "CognitoIdentity": {
                "Default": {
                    "PoolId": "XX-XXXX-X:XXXXXXXX-XXXX-1234-abcd-1234567890ab",
                    "Region": "XX-XXXX-X"
                }
            }
        },
        "CognitoUserPool": {
            "Default": {
                "PoolId": "XX-XXXX-X_abcd1234",
                "AppClientId": "XXXXXXXX",
                "AppClientSecret": "XXXXXXXXX",
                "Region": "XX-XXXX-X"
            }
        }
    }
```

Make sure it looks like this.

**Comment by subhendukundu** [comment]
That was it. Gosh, Thank you so much. I was about to lose hope on it :)
I am going to play with this for few days now if I get stuck, I will open tickets or we can create a forum for help etc cause this plugin is really needed for aws and flutter.
For now, closing this ticket.
Thanks
