### ISSUE TITLE
Erro when Initialize function

### ISSUE THREAD

**Issue by gabuldev** [agnostech/flutter_amplify#9]
` Built build/app/outputs/apk/debug/app-debug.apk.
D/EGL_emulation(15585): eglMakeCurrent: 0x71113d2fdec0: ver 3 0 (tinfo 0x71113d349e80)
I/AWSKeyValueStore(15585): Detected Android API Level = 28
I/AWSKeyValueStore(15585): Creating the AWSKeyValueStore with key for sharedPreferencesForData = com.amazonaws.mobile.client
I/AWSKeyValueStore(15585): Detected Android API Level = 28
I/AWSKeyValueStore(15585): Creating the AWSKeyValueStore with key for sharedPreferencesForData = com.amazonaws.android.auth
I/flutter (15585): -- AppModule INITIALIZED
W/LogFactory(15585): Truncating log tag length as it exceed 23, the limit imposed by Android on certain API Levels
I/AWSKeyValueStore(15585): Detected Android API Level = 28
I/AWSKeyValueStore(15585): Creating the AWSKeyValueStore with key for sharedPreferencesForData = com.amazonaws.android.auth
E/AWSKeyValueStore(15585): com.amazonaws.internal.keyvaluestore.KeyNotFoundException: Error occurred while accessing AndroidKeyStore to retrieve the key for keyAlias: com.amazonaws.android.auth.aesKeyStoreAlias
I/AWSKeyValueStore(15585): Deleting the encryption key identified by the keyAlias: com.amazonaws.android.auth.aesKeyStoreAlias
E/AWSKeyValueStore(15585): Error in retrieving the decryption key used to decrypt the data from the persistent store. Returning null for the requested dataKey = us-east-2:5e250afa-df78-48d2-b678-7250444a2880.identityId
D/CognitoCachingCredentialsProvider(15585): Loading credentials from SharedPreferences
E/AWSKeyValueStore(15585): com.amazonaws.internal.keyvaluestore.KeyNotFoundException: Error occurred while accessing AndroidKeyStore to retrieve the key for keyAlias: com.amazonaws.android.auth.aesKeyStoreAlias
I/AWSKeyValueStore(15585): Deleting the encryption key identified by the keyAlias: com.amazonaws.android.auth.aesKeyStoreAlias
E/AWSKeyValueStore(15585): Error in retrieving the decryption key used to decrypt the data from the persistent store. Returning null for the requested dataKey = us-east-2:5e250afa-df78-48d2-b678-7250444a2880.expirationDate
D/CognitoCachingCredentialsProvider(15585): No valid credentials found in SharedPreferences
W/LogFactory(15585): Truncating log tag length as it exceed 23, the limit imposed by Android on certain API Levels
I/AWSKeyValueStore(15585): Detected Android API Level = 28
I/AWSKeyValueStore(15585): Creating the AWSKeyValueStore with key for sharedPreferencesForData = CognitoIdentityProviderCache
D/KeyProvider23(15585): AndroidKeyStore contains keyAlias com.amazonaws.mobile.client.aesKeyStoreAlias
D/KeyProvider23(15585): Loading the encryption key from Android KeyStore.
W/AWSMobileClient(15585): Failed to parse HostedUI settings from store. Defaulting to awsconfiguration.json
W/AWSMobileClient(15585): java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
W/AWSMobileClient(15585): 	at org.json.JSONTokener.nextCleanInternal(JSONTokener.java:116)
W/AWSMobileClient(15585): 	at org.json.JSONTokener.nextValue(JSONTokener.java:94)
W/AWSMobileClient(15585): 	at org.json.JSONObject.<init>(JSONObject.java:159)
W/AWSMobileClient(15585): 	at org.json.JSONObject.<init>(JSONObject.java:176)
W/AWSMobileClient(15585): 	at com.amazonaws.mobile.client.AWSMobileClient.getHostedUIJSON(AWSMobileClient.java:663)
W/AWSMobileClient(15585): 	at com.amazonaws.mobile.client.AWSMobileClient$2.run(AWSMobileClient.java:565)
W/AWSMobileClient(15585): 	at com.amazonaws.mobile.client.internal.InternalCallback$1.run(InternalCallback.java:101)
`

**Comment by vishal-android-freak** [comment]
Let me have a look at this! Will revert at the earliest
